version: "3.8"

services:
  web:
    image: nginx:1.20-alpine
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      # nginx config
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"

      # backend
      - "./:/var/www/html"
    depends_on:
      - app

  app:
    build: .
    restart: unless-stopped
    volumes:
      - "./:/var/www/html"

  # db:
  #   build: mysql:8
  #   restart: unless-stopped
  #   ports:
  #     - 3306:3306
  #   env_file:
  #     - ./docker/mysql/.env
  #   volumes:
  #     - maindb:/var/lib/mysql # ./docker/mysql/volumes/data:/var/lib/mysql

networks:
  default:
    external: true
    name: puplqvoting-network
